"""The registry as the docs see it: ``robots.json`` plus the URDF long tail.

``strands_robots/registry/robots.json`` is the curated registry. ``urdf_robots.json``
next to it, generated by ``scripts/build_urdf_registry.py`` from assets the URDF
loader built, lists the ``robot_descriptions`` robots that have a URDF and no
MJCF sibling and no curated entry; ``Robot("<name>", mode="sim")`` compiles them
for MuJoCo on first use. Both files are what ``list_robots()`` reports, so both
are what the docs describe: this module merges them into the one mapping every
hook consumes (a curated name always wins, which the generator guarantees
anyway), with each URDF entry given the shape of a curated one plus
``source: "urdf"``.

Filesystem only: no ``strands_robots`` import, so the docs build works without
the package installed. The entry shape mirrors
``strands_robots.registry.discovery._urdf_entry``; ``tests/registry`` grades
that the two agree.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
_REGISTRY_DIR = _REPO / "strands_robots" / "registry"
ROBOTS_JSON = _REGISTRY_DIR / "robots.json"
URDF_ROBOTS_JSON = _REGISTRY_DIR / "urdf_robots.json"

#: Value of ``source`` on a merged URDF entry (curated entries carry ``"curated"``).
URDF_SOURCE = "urdf"


def urdf_entry(name: str, rec: dict) -> dict:
    """A ``urdf_robots.json`` row as a registry entry (see ``discovery._urdf_entry``)."""
    module = rec["module"]
    entry: dict = {
        "description": f"{name} ({' '.join(rec.get('tags', ())) or 'robot'} URDF from robot_descriptions)",
        "category": rec["category"],
        "discovered": True,
        "source": URDF_SOURCE,
        "floating": bool(rec.get("floating", False)),
        "tags": list(rec.get("tags", ())),
    }
    if rec.get("joints") is not None:
        entry["joints"] = int(rec["joints"])
    if rec.get("has_sim", True):
        entry["asset"] = {
            "dir": module,
            "model_xml": "robot.xml",
            "scene_xml": "scene.xml",
            "info_json": "urdf_asset.json",
            "robot_descriptions_module": module,
            "source": {"type": URDF_SOURCE},
        }
        for key in ("repository", "commit", "mesh_formats", "streamable", "nq"):
            if key in rec:
                entry[key] = rec[key]
    else:
        entry["refusal"] = str(rec.get("refusal", "the description does not build"))
    return entry


@lru_cache(maxsize=1)
def curated() -> dict[str, dict]:
    """``robots.json`` alone, keyed by canonical name."""
    return json.loads(ROBOTS_JSON.read_text(encoding="utf-8"))["robots"]


@lru_cache(maxsize=1)
def urdf_robots() -> dict[str, dict]:
    """``urdf_robots.json`` rows as registry entries; empty when the file is absent."""
    if not URDF_ROBOTS_JSON.exists():
        return {}
    rows = json.loads(URDF_ROBOTS_JSON.read_text(encoding="utf-8"))["robots"]
    return {name: urdf_entry(name, rec) for name, rec in sorted(rows.items())}


@lru_cache(maxsize=1)
def merged() -> dict[str, dict]:
    """Every robot ``Robot("<name>")`` accepts by name: curated first, then the URDF tail."""
    out = {name: {**spec, "source": spec.get("source", "curated")} for name, spec in curated().items()}
    for name, spec in urdf_robots().items():
        out.setdefault(name, spec)
    return out
