#!/usr/bin/env python3
"""Render the scene a docs fence builds, from the fence itself, into docs/assets/sim.

A page that builds a scene should show the scene. This script runs a page's own
runnable ``python`` fence (the same source ``check_fences.py`` runs) in a fresh
interpreter with MuJoCo offscreen, and when the fence's engine is cleaned up (or
the interpreter exits) it renders one frame from a camera framed on every body in
the world and writes ``docs/assets/sim/<id>.png``. The page then places the frame
with ``{{sim:<id>|caption}}`` (see :mod:`visuals`), directly under the fence.

Which fences produce a frame is declared in ``docs/hooks/data/sim_frames.json``::

    {"first-robot-1": {"page": "start/first-robot.md", "fence": 2},
     "talk-to-it": {"script": "docs/hooks/transcripts/talk_to_it.py", "page": "start/first-agent.md",
                    "frames": ["talk-to-it-1", "talk-to-it-2"]}}

``fence`` is the 1-based index among the page's runnable fences, as
``check_fences.py`` numbers them. A ``script`` entry runs a capture script (an agent
transcript, say) that writes the listed frames itself. Frames are committed: the build needs no GPU,
no display and no MuJoCo; ``--check`` reports a manifest entry with no frame or
a frame with no entry, which is what ``tests/test_docs_visual_tokens_resolve.py``
grades against the pages.

    python3 docs/hooks/sim_frames.py                # every entry
    python3 docs/hooks/sim_frames.py first-robot-1  # one
    python3 docs/hooks/sim_frames.py --check

Rendering is deterministic for a deterministic fence (fixed camera, fixed size),
so a re-run on the same commit reproduces the file byte for byte on one host;
across MuJoCo or GL versions it may differ by a few pixels, which is why frames
are regenerated by hand, not graded for equality.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DOCS = REPO / "docs"
MANIFEST = DOCS / "hooks" / "data" / "sim_frames.json"
OUT = DOCS / "assets" / "sim"
FENCE = re.compile(r"^```python[ \t]*\n(.*?)^```[ \t]*$", re.M | re.S)
TIMEOUT_S = 180
WIDTH, HEIGHT = 960, 540

# Runs inside the fence's interpreter, before the fence. It wraps the MuJoCo engine's
# cleanup so the last thing the fence does is photographed, and photographs at exit
# any engine the fence never cleaned up.
_PRELUDE = r'''
import atexit, os, sys
_OUT = os.environ["STRANDS_DOCS_FRAME"]
_W, _H = int(os.environ["STRANDS_DOCS_FRAME_W"]), int(os.environ["STRANDS_DOCS_FRAME_H"])
_live = []
_done = {"shot": False}

def _frame_camera(engine):
    """Position and target framing every body in the world: centre of the body
    positions, distance from their spread, looking from the front right and above."""
    import numpy as np
    data, model = engine.mj_data, engine.mj_model
    pts = np.asarray(data.xpos[1:]) if model.nbody > 1 else np.zeros((1, 3))
    lo, hi = pts.min(axis=0), pts.max(axis=0)
    centre = (lo + hi) / 2
    radius = max(float(np.linalg.norm(hi - lo)) / 2, 0.15)
    direction = np.array([1.7, -1.4, 0.95])
    position = centre + direction / np.linalg.norm(direction) * radius * 3.2
    target = centre + np.array([0.0, 0.0, radius * 0.15])
    return [float(x) for x in position], [float(x) for x in target]

def _shoot(engine):
    if _done["shot"]:
        return
    try:
        position, target = _frame_camera(engine)
        engine.add_camera(name="docs_frame", position=position, target=target, fov=45.0, width=_W, height=_H)
        frame = engine.render(camera_name="docs_frame")
        png = next(b["image"]["source"]["bytes"] for b in frame["content"] if "image" in b)
        with open(_OUT, "wb") as f:
            f.write(png)
        _done["shot"] = True
    except Exception as exc:  # the fence's own output matters more than the frame
        print(f"[sim_frames] no frame: {exc!r}", file=sys.stderr)

def _install():
    from strands_robots.simulation.mujoco import simulation as _sim
    Engine = _sim.MuJoCoSimEngine
    orig_init, orig_cleanup = Engine.__init__, Engine.cleanup
    def __init__(self, *a, **k):
        orig_init(self, *a, **k)
        _live.append(self)
    def cleanup(self, *a, **k):
        _shoot(self)
        return orig_cleanup(self, *a, **k)
    Engine.__init__, Engine.cleanup = __init__, cleanup
    atexit.register(lambda: [_shoot(e) for e in _live])

_install()
'''


def runnable_fences(page: Path) -> list[str]:
    """The bare ``python`` fences of a page, in order, as check_fences.py numbers them."""
    return [m.group(1) for m in FENCE.finditer(page.read_text(encoding="utf-8"))]


def render_script(ident: str, entry: dict, python: str) -> bool:
    """Run a capture script (``docs/hooks/transcripts/*.py``) that writes its own frames.

    The script gets ``STRANDS_DOCS_FRAME_DIR`` and writes ``<ident>-<n>.png`` plus its
    transcript; the manifest entry lists the frames it expects under ``frames``.
    """
    OUT.mkdir(parents=True, exist_ok=True)
    env = dict(os.environ)
    env.update(
        PYTHONPATH=str(REPO),
        MUJOCO_GL=env.get("MUJOCO_GL", "cgl" if sys.platform == "darwin" else "egl"),
        STRANDS_DOCS_FRAME_DIR=str(OUT),
    )
    proc = subprocess.run(
        [python, str(REPO / entry["script"])],
        cwd=tempfile.gettempdir(),
        env=env,
        capture_output=True,
        text=True,
        timeout=entry.get("timeout_s", 900),
        check=False,
    )
    missing = [f for f in entry["frames"] if not (OUT / f"{f}.png").is_file()]
    if proc.returncode != 0 or missing:
        print(f"{ident}: FAIL (exit {proc.returncode}, missing {missing})\n{proc.stderr[-1500:]}")
        return False
    print(f"{ident}: {len(entry['frames'])} frames from {entry['script']}")
    return True


def expected_frames(manifest: dict) -> set[str]:
    """Every frame id the manifest promises: one per fence entry, a list per script entry."""
    out: set[str] = set()
    for ident, entry in manifest.items():
        out |= set(entry["frames"]) if "script" in entry else {ident}
    return out


def render_one(ident: str, entry: dict, python: str) -> bool:
    """Run one manifest entry's fence and write its frame; False when either fails."""
    if "script" in entry:
        return render_script(ident, entry, python)
    page = DOCS / entry["page"]
    fences = runnable_fences(page)
    index = int(entry["fence"])
    if not 1 <= index <= len(fences):
        print(f"{ident}: {entry['page']} has {len(fences)} runnable fences, no #{index}")
        return False
    OUT.mkdir(parents=True, exist_ok=True)
    target = OUT / f"{ident}.png"
    env = dict(os.environ)
    env.update(
        PYTHONPATH=str(REPO),
        MUJOCO_GL=env.get("MUJOCO_GL", "cgl" if sys.platform == "darwin" else "egl"),
        STRANDS_DOCS_FRAME=str(target),
        STRANDS_DOCS_FRAME_W=str(entry.get("width", WIDTH)),
        STRANDS_DOCS_FRAME_H=str(entry.get("height", HEIGHT)),
    )
    with tempfile.TemporaryDirectory() as tmp:
        script = Path(tmp) / f"{ident}.py"
        script.write_text(_PRELUDE + "\n" + fences[index - 1], encoding="utf-8")
        proc = subprocess.run(
            [python, str(script)], cwd=tmp, env=env, capture_output=True, text=True, timeout=TIMEOUT_S, check=False
        )
    if proc.returncode != 0 or not target.is_file():
        print(f"{ident}: FAIL (exit {proc.returncode})\n{proc.stderr[-1500:]}")
        return False
    print(f"{ident}: {target.relative_to(REPO)} ({target.stat().st_size // 1024} KB) from {entry['page']} #{index}")
    return True


def check(manifest: dict) -> int:
    """Exit 1 when a manifest entry has no frame or a frame has no entry."""
    frames = {p.stem for p in OUT.glob("*.png")} if OUT.is_dir() else set()
    promised = expected_frames(manifest)
    missing = sorted(promised - frames)
    extra = sorted(frames - promised)
    for ident in missing:
        print(f"no frame for manifest entry {ident}: run docs/hooks/sim_frames.py {ident}")
    for ident in extra:
        print(f"frame with no manifest entry: docs/assets/sim/{ident}.png")
    return 1 if missing or extra else 0


def main(argv: list[str] | None = None) -> int:
    """Render the requested frames (or check them); return the exit code."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("ids", nargs="*", help="manifest ids to render (default: all)")
    parser.add_argument("--check", action="store_true", help="report manifest/frame mismatches, render nothing")
    parser.add_argument("--python", default=sys.executable, help="interpreter that has strands-robots[sim-mujoco]")
    args = parser.parse_args(argv)
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if args.check:
        return check(manifest)
    ids = args.ids or sorted(manifest)
    unknown = [i for i in ids if i not in manifest]
    if unknown:
        print(f"not in {MANIFEST.relative_to(REPO)}: {unknown}")
        return 2
    ok = all(render_one(i, manifest[i], args.python) for i in ids)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
