"""``docs/robots/earthrover.md`` teaches the EarthRover SDK on the port the SDK binds.

The earth-rovers-sdk has one bind (``hypercorn main:app --bind 0.0.0.0:8000``)
and :data:`~strands_robots.drivers.earthrover.DEFAULT_SDK_URL` dials it. The old
``docs/robots/mobile.md`` hardware fence and its ``port`` table spelled every
address on ``:8001``, so a reader who copied ``port="http://10.0.0.9:8001"`` for
a stock SDK got the same "unreachable" report the old default gave. The robot
now has its own page, generated by ``docs/hooks/robot_pages.py`` from the
registry and committed; its ``Robot("earthrover", ..., port=...)`` fence is
graded here, and so is the hook's ``DRIVERS`` entry the drivers page renders
(every port literal in it), both against the driver's own default.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path
from urllib.parse import urlsplit

import strands_robots
from strands_robots.drivers.earthrover import DEFAULT_SDK_URL
from tests._docs_hooks import docs_hook

_REPO = Path(strands_robots.__file__).resolve().parent.parent
_PAGE = _REPO / "docs" / "robots" / "earthrover.md"
_PYTHON_FENCE = re.compile(r"```python[^\n]*\n(.*?)```", re.DOTALL)  # fences may carry title="..."
_PORT_LITERAL = re.compile(r":(\d{2,5})(?=[/\s`\"',|)]|$)")


def _fence_earthrover_ports() -> list[int]:
    ports: list[int] = []
    for fence in _PYTHON_FENCE.findall(_PAGE.read_text(encoding="utf-8")):
        try:
            tree = ast.parse(fence)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not (isinstance(node, ast.Call) and getattr(node.func, "id", None) == "Robot"):
                continue
            if not (node.args and isinstance(node.args[0], ast.Constant) and node.args[0].value == "earthrover"):
                continue
            # The page also shows the lerobot build of the same robot, whose
            # ``port=`` is a serial device; only the native driver dials the SDK.
            drivers = {
                kw.value.value for kw in node.keywords if kw.arg == "driver" and isinstance(kw.value, ast.Constant)
            }
            if drivers != {"strands"}:
                continue
            for kw in node.keywords:
                if kw.arg == "port" and isinstance(kw.value, ast.Constant) and isinstance(kw.value.value, str):
                    ports.append(urlsplit(kw.value.value).port or -1)
    return ports


def test_earthrover_fence_port_is_the_sdk_bind() -> None:
    ports = _fence_earthrover_ports()
    assert ports, "earthrover.md has no Robot('earthrover', ..., port=...) fence"
    assert set(ports) == {urlsplit(DEFAULT_SDK_URL).port}


def _earthrover_facts() -> str:
    """The driver's ``port=`` facts: the text the drivers page renders for EarthRoverDriver.

    Robot pages link to that one section instead of restating it, so the
    hook's ``DRIVERS`` entry is the whole claim about the SDK address.
    """
    module = docs_hook("robot_pages")
    facts = module.DRIVERS["EarthRoverDriver"]
    return f"{facts['port']} {facts['example']}"


def test_every_port_literal_in_the_earthrover_facts_is_the_sdk_bind() -> None:
    sdk_port = str(urlsplit(DEFAULT_SDK_URL).port)
    found = _PORT_LITERAL.findall(_earthrover_facts())
    assert found, "the EarthRoverDriver facts spell no host:port address"
    assert set(found) == {sdk_port}
