"""The site has two lanes, and neither one loses a page.

A reader arriving from a link and an agent resolving a symbol want opposite
things from the same site. The nav used to serve both: eight sections, ninety
entries, ``Simulate`` and ``Real Hardware`` alone carrying twenty-four rows, so
the reader scrolled a table of contents longer than the page they landed on.

The split is by URL. ``docs/index.md``, ``getting-started/`` and ``robots/``
stay where they are and stay in the nav - that is the lane a newcomer reads.
Every page that states a contract lives under ``docs/reference/`` and is
reached from ``reference/index.md``, whose list is generated by
``docs/hooks/reference_index.py`` from the tree.

Three ways that arrangement can quietly break, each graded here:

* **A page falls out of both lanes.** MkDocs reports a page missing from the
  nav as ``INFO``, which ``--strict`` does not fail on, so an unnavigated page
  ships and is reachable only by search. The old guard demanded every page be
  in the nav, which a narrow nav can no longer satisfy; the rule is now that
  every page is reachable from the nav *or* from the generated index.
* **The nav grows back.** Adding a reference page to the sidebar is one line
  and undoes the split one line at a time, so the nav is held to Lane A plus
  the single pointer.
* **A published URL stops resolving.** Ninety-two pages moved under
  ``/reference/``, and every one of those URLs is in the wild - in a release
  note, an issue, a bookmark. ``mkdocs-redirects`` serves each old URL a
  redirect to its new home, and a redirect is graded both ways: its source must
  not be a page on disk (that would shadow a real page) and its destination
  must be.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
_DOCS = _REPO / "docs"
_MKDOCS = _REPO / "mkdocs.yml"

#: The lane a newcomer reads: these paths stay at the site root and in the nav.
LANE_A = ("index.md", "getting-started/", "robots/")

#: The one nav entry that points into the reference lane.
LANE_B_POINTER = "reference/index.md"

#: Pages born under ``docs/reference/`` - they never had a root URL, so they
#: are the only reference pages that owe no redirect. A new page added here
#: belongs in this tuple; a page *moved* here needs a redirect instead.
BORN_IN_REFERENCE = ("reference/index.md", "reference/tools.md", "reference/configuration.md")

#: A redirect map that shrank to nothing would satisfy every rule below.
MINIMUM_REDIRECTS = 80

_NAV_ITEM = re.compile(r"^(?P<indent> *)- (?P<body>.+?)\s*$")
_REDIRECT_ROW = re.compile(r"^ {6}(?P<source>[\w./-]+\.md): (?P<target>[\w./-]+\.md)$", re.M)
_LINK = re.compile(r"\[[^\]]*\]\((?P<target>[^)\s]+)\)")


def _hook():
    """The reference-index hook, loaded from the tree the build loads it from."""
    name = "docs_reference_index_hook"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, _REPO / "docs/hooks/reference_index.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _nav_targets() -> list[str]:
    """Every page path the nav points at, in nav order."""
    lines = _MKDOCS.read_text(encoding="utf-8").splitlines()
    targets: list[str] = []
    for line in lines[lines.index("nav:") + 1 :]:
        if not line.strip():
            continue
        if not line.startswith((" ", "-")):
            break
        match = _NAV_ITEM.match(line)
        assert match, f"mkdocs.yml nav line is not a list item: {line!r}"
        body = match["body"]
        target = body.split(":", 1)[1].strip() if ":" in body else body
        if target:
            targets.append(target)
    assert targets, "no nav entries parsed out of mkdocs.yml"
    return targets


def _redirects() -> dict[str, str]:
    """The ``redirect_maps`` table as ``{old page: new page}``."""
    config = _MKDOCS.read_text(encoding="utf-8")
    block = config.split("redirect_maps:", 1)
    assert len(block) == 2, "mkdocs.yml declares no redirect_maps; moved URLs resolve to nothing"
    return {m["source"]: m["target"] for m in _REDIRECT_ROW.finditer(block[1])}


def _pages() -> set[str]:
    """Every page under ``docs/``, as a docs-relative posix path."""
    return {p.relative_to(_DOCS).as_posix() for p in _DOCS.rglob("*.md")}


def _indexed() -> list[str]:
    """Every page the generated reference index links to, as a docs path."""
    rendered = _hook().render()
    return [f"reference/{m['target']}" for m in _LINK.finditer(rendered)]


class TestNeitherLaneLosesAPage:
    """Every page is reachable, and the nav stays Lane A wide."""

    def test_every_page_is_reachable_from_the_nav_or_the_reference_index(self) -> None:
        reachable = set(_nav_targets()) | set(_indexed()) | {LANE_B_POINTER}
        orphans = sorted(_pages() - reachable)
        assert not orphans, (
            f"pages under docs/ that neither the nav nor the reference index reaches: "
            f"{orphans}. A page nothing links to is found only by search: put it in the "
            f"nav if a newcomer needs it, or under docs/reference/ where the index picks "
            f"it up."
        )

    def test_the_nav_holds_lane_a_and_one_pointer_at_the_reference(self) -> None:
        strays = [t for t in _nav_targets() if not t.startswith(LANE_A) and t != LANE_B_POINTER]
        assert not strays, (
            f"mkdocs.yml nav points at reference pages: {strays}. The sidebar carries the "
            f"pages a newcomer reads plus {LANE_B_POINTER}; a contract page is reached from "
            f"the reference index, which lists it already."
        )
        assert LANE_B_POINTER in _nav_targets(), (
            f"mkdocs.yml nav no longer points at {LANE_B_POINTER}; the reference lane would "
            f"be reachable only by search."
        )


class TestTheReferenceIndexIsTheTree:
    """The generated list and the directory agree, both ways."""

    def test_it_lists_every_reference_page_exactly_once(self) -> None:
        on_disk = sorted(p for p in _pages() if p.startswith("reference/") and p != LANE_B_POINTER)
        indexed = _indexed()
        assert sorted(indexed) == on_disk, (
            f"the generated reference index and docs/reference/ disagree: "
            f"missing {sorted(set(on_disk) - set(indexed))}, "
            f"extra {sorted(set(indexed) - set(on_disk))}."
        )
        assert len(indexed) == len(set(indexed)), "the reference index lists a page twice"

    def test_every_entry_carries_the_page_title(self) -> None:
        hook = _hook()
        rendered = hook.render()
        for page in hook.pages():
            title = hook.title_of(page)
            href = page.relative_to(_DOCS / "reference").as_posix()
            assert f"[{title}]({href})" in rendered, (
                f"the reference index does not link {href} under its own title {title!r}"
            )


class TestEveryMovedUrlStillResolves:
    """A redirect for each retired URL, pointing at a page that exists."""

    def test_every_reference_page_that_moved_has_a_redirect(self) -> None:
        moved = sorted(p for p in _pages() if p.startswith("reference/") and p not in BORN_IN_REFERENCE)
        redirects = _redirects()
        missing = [p for p in moved if redirects.get(p[len("reference/") :]) != p]
        assert not missing, (
            f"pages under docs/reference/ whose old URL redirects nowhere: {missing}. Add "
            f"'<old path>: reference/<old path>' to mkdocs.yml redirect_maps, or name the "
            f"page in BORN_IN_REFERENCE if it never had a root URL."
        )
        assert len(redirects) >= MINIMUM_REDIRECTS, (
            f"redirect_maps holds {len(redirects)} entries; the move retired "
            f"{MINIMUM_REDIRECTS}+ URLs and each one is in the wild."
        )

    def test_no_redirect_shadows_a_page_or_points_at_a_missing_one(self) -> None:
        pages = _pages()
        shadowing = sorted(source for source in _redirects() if source in pages)
        assert not shadowing, (
            f"redirect_maps sources that are real pages: {shadowing}. A redirect at a live "
            f"URL hides the page it sits on."
        )
        dangling = sorted(target for target in _redirects().values() if target not in pages)
        assert not dangling, f"redirect_maps targets that are not pages on disk: {dangling}"
