"""U16: UI selection -> a Python file that recreates the exact peer elsewhere.

The dashboard's spawn form and the profile store both describe a rig as a
payload dict (robot_name/mode/port/cameras/robot_id/peer_id). This renders
that payload as a copy-pasteable ``strands_robots`` script whose factory call
mirrors the dashboard's own child spawner (device_manager._SPAWNER) line for
line - same env posture, same eager connect, same keep-alive - so "runs as a
dashboard child" and "runs on an edge device" are the same object, not two
programs that drift apart.

Pure module: no I/O, no imports from the dashboard app. The route feeds it
either a saved profile or the live form state; tests feed it dicts.
"""

from __future__ import annotations

import time
from typing import Any, Mapping

__all__ = ["render_snippet", "snippet_filename"]

#: Env the dashboard's own spawner sets. Rendered as setdefault so an edge
#: box with a deliberate different posture (real ACL file, mTLS) wins.
_MESH_ENV: tuple[tuple[str, str], ...] = (
    ("STRANDS_ROBOTS_NO_DYLD_SHIM", "1"),
    ("STRANDS_MESH_LOCAL_DEV", "1"),
    ("STRANDS_MESH_MULTICAST", "true"),
    ("STRANDS_MESH", "true"),
    ("STRANDS_MESH_CAMERA_HZ", "5"),
)


def snippet_filename(peer_id: str) -> str:
    """A filename safe to offer as a download, derived from the peer id."""
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in peer_id)
    return f"{safe or 'robot'}.py"


def _fmt(value: Any, indent: int = 0) -> str:
    """Render a payload value as Python source (JSON types only).

    ``repr`` is almost right but renders dict one-line; camera configs are
    nested and read better expanded. Only handles what a spawn payload can
    legally contain - str/int/float/bool/None/dict - because the payload was
    validated by the same rules the spawn route applies.
    """
    if isinstance(value, Mapping):
        if not value:
            return "{}"
        pad = " " * (indent + 4)
        items = ",\n".join(f"{pad}{k!r}: {_fmt(v, indent + 4)}" for k, v in value.items())
        return "{\n" + items + ",\n" + " " * indent + "}"
    return repr(value)


def render_snippet(
    payload: Mapping[str, Any],
    *,
    hub_host: str | None = None,
    now: float | None = None,
) -> dict[str, Any]:
    """Render a spawn payload/profile as a deployable Python script.

    Refuses (``{"error": ...}``) instead of guessing when the payload cannot
    describe a runnable robot - a generated file that starts the WRONG rig is
    worse than no file.

    ``hub_host`` is the address edge devices reach THIS dashboard's zenoh hub
    on; rendered into ``ZENOH_CONNECT``. None means same-machine deploy and
    the line is emitted commented out, showing where the host goes.
    """
    robot_name = str(payload.get("robot_name") or "").strip()
    if not robot_name:
        return {"error": "payload has no robot_name"}
    mode = str(payload.get("mode") or "").strip()
    if mode not in ("real", "sim"):
        return {"error": f"mode must be real or sim, got {mode!r}"}
    port = payload.get("port")
    if mode == "real" and not port:
        return {"error": "port required for mode=real"}
    peer_id = str(payload.get("peer_id") or payload.get("name") or "").strip()
    if not peer_id:
        return {"error": "payload has no peer_id"}

    stamp = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime(now if now is not None else time.time()))
    name = payload.get("name") or peer_id

    lines: list[str] = ["#!/usr/bin/env python3", f'"""{name} - generated by the strands-robots dashboard, {stamp}.']
    lines += [
        "",
        "Recreates this exact rig on any machine with strands-robots installed:",
        "",
        "    pip install strands-robots",
        f"    python {snippet_filename(peer_id)}",
        "",
    ]
    role = payload.get("role")
    if role in ("leader", "follower") and payload.get("role_source") == "measured":
        volts = payload.get("role_volts")
        volts_txt = f" at {volts}V" if volts is not None else ""
        lines.append(f"This arm measured as the {role.upper()}{volts_txt} on its servo bus.")
        lines.append("")
    if payload.get("cameras"):
        lines.append("Camera indices are PER-MACHINE: index 1 here may be index 0 on the")
        lines.append("edge device. Re-check them there (lerobot-find-cameras opencv).")
        lines.append("")
    lines[-1] = lines[-1] if lines[-1] else '"""'
    if lines[-1] != '"""':
        lines.append('"""')
    lines += ["", "import os", "import time", ""]

    lines.append("# The mesh posture this dashboard runs with (setdefault: your own env wins).")
    for key, val in _MESH_ENV:
        lines.append(f'os.environ.setdefault("{key}", "{val}")')
    if hub_host:
        lines.append("# Reach this dashboard's zenoh hub from the edge device:")
        lines.append(f'os.environ.setdefault("ZENOH_CONNECT", "tcp/{hub_host}:7447")')
    else:
        lines.append("# Deploying to ANOTHER machine? Point the peer at this dashboard's hub:")
        lines.append('# os.environ.setdefault("ZENOH_CONNECT", "tcp/<dashboard-host>:7447")')
    lines += ["", "from strands_robots import Robot", "", "robot = Robot("]
    lines.append(f"    {robot_name!r},")
    lines.append(f"    mode={mode!r},")
    if mode == "real":
        serial = payload.get("serial_number")
        comment = f"  # USB serial {serial}" if serial and serial != port else ""
        lines.append(f"    port={str(port)!r},{comment}")
    if payload.get("robot_id"):
        lines.append(f"    id={str(payload['robot_id'])!r},  # lerobot calibration identity")
    cameras = payload.get("cameras")
    if cameras:
        lines.append(f"    cameras={_fmt(cameras, 4)},")
    lines.append("    mesh=True,")
    lines.append(f"    peer_id={peer_id!r},")
    lines.append(")")
    if mode == "real":
        lines += [
            "",
            "# Connect eagerly so joints + camera frames publish immediately (a camera",
            "# this machine will not open costs the camera, not the whole arm).",
            "ok, degraded, err = robot.connect_eagerly()",
            "for cam, reason in (degraded or {}).items():",
            '    print(f"camera {cam!r} unavailable, dropped: {reason}")',
            "if not ok:",
            '    print(f"eager connect failed (will retry on first task): {err}")',
        ]
    lines += [
        "",
        f'print("{peer_id} online - visible on the dashboard fleet")',
        "while True:",
        "    time.sleep(1)",
        "",
    ]
    return {
        "snippet": "\n".join(lines),
        "filename": snippet_filename(peer_id),
        "peer_id": peer_id,
    }
