"""Generate the CARD-EXTRA.md that publish.py appends, FROM the measured JSONs.

Written for it25's noise pair. Every number below is read out of a file produced by a gate run, so a
card cannot drift from its evidence by my retyping it. The one thing this file must say loudly is the
thing it24 nearly got wrong: a negative split's goal shortcut is a property of the PAIR, so the card
has to name the only pairing its number was measured on.
"""
from __future__ import annotations
import json, os, sys

DATA = os.path.expanduser("~/svla-rlenv-data")
RUNS = os.path.expanduser("~/.tiny/strands-vla-20261009/lanes/RLENV/runs")
PREFIX = "cagataydev/strands-vla-rlenv-"


def load(p):
    try:
        return json.load(open(p))
    except Exception:
        return None


def main(argv=None):
    pos, neg = "so100-push-NOISE", "so100-push-NOISE-FAIL"
    sep = load(f"{RUNS}/start-sep-NOISE-PAIR.json")
    cross = load(f"{RUNS}/start-sep-so100-push-NOISE-FAIL.json")
    if not sep:
        print(json.dumps({"refused": "no start-sep-NOISE-PAIR.json"}))
        return 1
    out = {}
    for shard, other, role in ((pos, neg, "successes"), (neg, pos, "failures")):
        rep = load(f"{DATA}/{shard}/GEN-REPORT.json") or {}
        vg = load(f"{RUNS}/verify-goals-{shard}.json") or {}
        pa = rep.get("passA", {})
        L = []
        L.append("")
        L.append("## Matched pair: this shard is half of an experiment")
        L.append("")
        L.append(f"Both shards were generated by the SAME policy under the SAME perturbation "
                 f"(`harvest.py --action-noise {rep.get('action_noise_rad')}` rad of Gaussian noise on the "
                 f"commanded joint targets), from the same seed stream. This one keeps the **{role}**.")
        L.append("")
        L.append(f"- companion: `{PREFIX}{other}` -- the {'failures' if role=='successes' else 'successes'} "
                 f"of the same run. **It is the only admissible counterpart for this shard.**")
        L.append(f"- seed overlap between the two shards: **{sep.get('seed_overlap')}** (an episode is in "
                 f"exactly one of them).")
        L.append(f"- this shard: {rep.get('passB',{}).get('recorded')} episodes / "
                 f"{rep.get('passB',{}).get('frames')} frames, single class "
                 f"{rep.get('passB',{}).get('single_class')}; pass-A rate {pa.get('keep_rate')} "
                 f"for {pa.get('keep_rate_is_for')} over {pa.get('tried')} tries.")
        L.append("")
        L.append("### How much of the label a goal-only probe can read (measured, 5-fold CV, 20 permutations)")
        L.append("")
        L.append("| features | AUC | permuted null (mean / max) |")
        L.append("|---|---|---|")
        for k in ("goal", "state", "both"):
            c = sep.get(k, {})
            L.append(f"| {k} | **{c.get('auc')}** | {c.get('permuted_mean')} / {c.get('permuted_max')} |")
        L.append("")
        s = sep.get("single", {})
        L.append(f"Single goal features: " + ", ".join(f"{k} {v}" for k, v in s.items()) + ".")
        L.append("")
        L.append(f"**Read this honestly.** Goal-only AUC is {sep.get('goal',{}).get('auc')}, which is well "
                 f"above the permuted null ({sep.get('goal',{}).get('permuted_max')} at worst), so the pair "
                 f"is NOT goal-balanced: where the cube starts still predicts the outcome, mostly through "
                 f"lateral position. What the perturbation bought is the drop from "
                 f"{(cross or {}).get('goal',{}).get('auc')} -- the AUC between these failures and the "
                 f"sigma=0 success shard `{PREFIX}so100-push` -- to {sep.get('goal',{}).get('auc')} here, "
                 f"and the pre-registered bar for publishing was 0.75.")
        L.append("")
        L.append("### Do not re-pair it")
        L.append("")
        L.append(f"Pairing these failures with `{PREFIX}so100-push` (the sigma=0 successes) puts the "
                 f"shortcut back: goal AUC **{(cross or {}).get('goal',{}).get('auc')}**, because that "
                 f"success set is itself goal-selected -- the hard goals are exactly the ones that failed at "
                 f"sigma=0. A negative split's shortcut is a property of the PAIR, not of the negatives. "
                 f"That cross-condition pairing failed this lane's gate and is recorded as such.")
        L.append("")
        L.append("### Goal provenance under noise")
        L.append("")
        L.append(f"`verify_goals.py --action-noise {rep.get('action_noise_rad')}` reproduces each checked "
                 f"episode's recorded first action as (expert plan replanned from the sidecar cube pose) + "
                 f"(the seeded per-episode noise draw): max |delta| "
                 f"**{vg.get('max_abs_delta')}** <= tol {vg.get('tol')}, "
                 f"{len(vg.get('failures') or [])} failures over {vg.get('n_checked')} episodes. So the "
                 f"noise is not an unlabelled corruption: it is reproducible from the seed, which also "
                 f"checks the sigma and the joint order.")
        L.append("")
        cmp_ = load(f"{RUNS}/necessity-noise-compare-{rep.get('arm')}-{rep.get('task')}.json")
        if cmp_:
            L.append("### Is the goal still NECESSARY under the noise (matched control)")
            L.append("")
            L.append(f"`goal_necessity.py --action-noise` runs the goal-aware expert and a goal-BLIND one "
                     f"(plans to the box centre, cube left where it is) at {cmp_.get('episodes_per_cell')} "
                     f"episodes per cell, band scale 1.0:")
            L.append("")
            L.append("| sigma | goal-aware | goal-blind | headroom |")
            L.append("|---|---|---|---|")
            for k in ("sigma0", "sigma0.05"):
                c = cmp_.get(k, {})
                L.append(f"| {k.replace('sigma','')} | {c.get('aware')} | {c.get('blind')} | "
                         f"**{c.get('headroom')}** |")
            L.append("")
            L.append(f"Neither difference is resolvable at this n (Fisher two-sided: aware "
                     f"{cmp_.get('aware_sigma0_vs_sigma005_fisher')}, blind "
                     f"{cmp_.get('blind_sigma0_vs_sigma005_fisher')}), so the honest reading is that the "
                     f"noise leaves push's goal-necessity UNCHANGED, not that it improves it. That is the "
                     f"expected behaviour for this criterion: push success is a TERMINAL displacement "
                     f"(cube_final - cube_start, projected on the approach axis), so jitter cannot buy "
                     f"extra chances. The touch criterion in this project is a MINIMUM over the episode, "
                     f"and there the same noise lifts a goal-blind expert from 0.14 to 0.47. A criterion "
                     f"that is an extremum over the trajectory is gameable by jitter; one read at a fixed "
                     f"time is not.")
            L.append("")
        L.append("### What this pair is FOR")
        L.append("")
        L.append("A success/failure pair from one policy, so a consumer can train or probe on outcome "
                 "without the outcome being a restatement of the goal. It is NOT a demonstration set: the "
                 "failures are failures, and the successes were produced with noise on the actions, so they "
                 "are less clean than the sigma=0 shard. For imitation data use "
                 f"`{PREFIX}so100-push`.")
        p = f"{DATA}/{shard}/CARD-EXTRA.md"
        open(p, "w").write("\n".join(L) + "\n")
        out[shard] = {"file": p, "lines": len(L)}
    print(json.dumps(out, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
