#!/usr/bin/env python3
"""Generate the cross-arm PRICE TABLE for noise-perturbed negative pairs, from the gate JSONs only.

Every row is read from files written by goal_necessity.py (--action-noise and its sigma=0 control) and
start_separability.py. Nothing here is typed by hand, so the published table cannot drift from the
evidence, and an arm with a missing cell is reported as missing rather than guessed.

The claim under test (it26, pre-registered for koch in PREREG-it27.md): the fraction of expert
competence a perturbation costs an arm predicts how goal-decoupled that arm's success/failure pair
becomes. It is reported here as HOLDS / FALSIFIED by the ordering, never asserted.
"""
import argparse, glob, json, os

RUNS = os.path.expanduser("~/.tiny/strands-vla-20261009/lanes/RLENV/runs")


def load(p):
    try:
        with open(p) as f:
            return json.load(f)
    except Exception:
        return None


def rows(runs):
    out = []
    for p in sorted(glob.glob(f"{runs}/necessity-noise-compare-*.json")):
        c = load(p)
        if not c:
            continue
        arm, task = c["arm"], c["task"]
        s0, s5 = c["sigma0"], c["sigma0.05"]
        sep = (load(f"{runs}/start-sep-NOISE-PAIR-{arm}.json")
               # the first arm's within-condition file predates the per-arm naming
               or (load(f"{runs}/start-sep-NOISE-PAIR.json") if arm == "so100" else None))
        # the cross-condition number (same failures vs the sigma=0 success shard) lives either inside
        # the within-condition JSON (later arms) or in its own file from the iteration that measured it
        # first (so100). Both locations are read; a missing one stays None rather than being filled in.
        cross = (sep or {}).get("cross_condition_goal_auc")
        if cross is None:
            x = load(f"{runs}/start-sep-{arm}-{task}-NOISE-FAIL.json")
            cross = (x or {}).get("goal", {}).get("auc")
        lost = None
        if s0["aware"]:
            lost = round(max(0.0, (s0["aware"] - s5["aware"]) / s0["aware"]), 3)
        out.append({
            "arm": arm, "task": task,
            "aware_sigma0": s0["aware"], "aware_sigma005": s5["aware"],
            "aware_fisher": c.get("aware_sigma0_vs_sigma005_fisher"),
            "headroom_sigma0": s0["headroom"], "headroom_sigma005": s5["headroom"],
            "competence_lost_fraction": lost,
            "pair_goal_auc": (sep or {}).get("goal", {}).get("auc"),
            "pair_goal_null_max": (sep or {}).get("goal", {}).get("permuted_max"),
            "pair_state_auc": (sep or {}).get("state", {}).get("auc"),
            "pair_state_inside_null": (sep or {}).get("state", {}).get("inside_permuted_spread"),
            "cross_condition_goal_auc": cross,
            "pair_scored": sep is not None,
        })
    return out


def verdict(rs):
    scored = [r for r in rs if r["pair_scored"] and r["competence_lost_fraction"] is not None]
    if len(scored) < 3:
        return {"status": "UNDECIDED", "why": f"only {len(scored)} arms have both a priced cell and a "
                                              f"scored pair; the ordering claim needs at least 3."}
    by_loss = sorted(scored, key=lambda r: r["competence_lost_fraction"])
    aucs = [r["pair_goal_auc"] for r in by_loss]
    mono = all(aucs[i] >= aucs[i + 1] for i in range(len(aucs) - 1))
    return {"status": "HOLDS" if mono else "FALSIFIED",
            "order_by_competence_lost": [(r["arm"], r["competence_lost_fraction"], r["pair_goal_auc"])
                                         for r in by_loss],
            "why": ("goal AUC falls monotonically as the fraction of expert competence lost rises"
                    if mono else
                    "goal AUC is NOT monotone in competence lost, so the amount of decoupling is not "
                    "predictable from the competence cost; it26's rule is withdrawn to a description "
                    "of the two arms it was measured on")}


def md(rs, v):
    L = ["# The price of a goal-decoupled negative split", "",
         "Generated by `price_table.py` from the gate JSONs in the lane's `runs/`; no number is typed.",
         "Perturbation is the same in every row: Gaussian noise, sigma = 0.05 rad, added to each",
         "commanded joint target, seeded per episode (so it is reproducible bit-exactly).", "",
         "| arm | task | expert sigma0 -> sigma0.05 | Fisher | headroom | competence lost | pair goal AUC"
         " (null max) | state AUC inside null | cross-condition goal AUC |",
         "|---|---|---|---|---|---|---|---|---|"]
    for r in rs:
        ga = r["pair_goal_auc"]
        L.append(f"| {r['arm']} | {r['task']} | {r['aware_sigma0']} -> {r['aware_sigma005']} | "
                 f"{r['aware_fisher']} | {r['headroom_sigma0']} -> {r['headroom_sigma005']} | "
                 f"{'n/a' if r['competence_lost_fraction'] is None else r['competence_lost_fraction']} | "
                 f"{'NOT SCORED' if ga is None else f'{ga} ({r['pair_goal_null_max']})'} | "
                 f"{r['pair_state_inside_null']} | {r['cross_condition_goal_auc']} |")
    L += ["", f"**Ordering claim: {v['status']}** -- {v['why']}.", ""]
    if v.get("order_by_competence_lost"):
        L.append("By competence lost (arm, fraction lost, pair goal AUC): "
                 + ", ".join(f"{a} {f} -> {g}" for a, f, g in v["order_by_competence_lost"]) + ".")
        L.append("")
    L += ["A pair is publishable when its goal AUC is below 0.75 and its state AUC sits inside its own",
          "permuted null; that gate is independent of the ordering claim above. The cross-condition",
          "column is the same failures scored against the sigma=0 success shard, and it is always the",
          "higher number: a negative split's shortcut is a property of the PAIR, not of the negatives.",
          "A cross-condition value at or above 0.75 means that pairing is NOT publishable even though the",
          "within-condition one is -- koch is exactly that case (0.7568 against 0.7236)."]
    return "\n".join(L) + "\n"


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--runs", default=RUNS)
    p.add_argument("--out", default=os.path.expanduser(
        "~/.tiny/strands-vla-20261009/lanes/RLENV/PRICE-TABLE.md"))
    p.add_argument("--json", default=None)
    a = p.parse_args(argv)
    rs = rows(a.runs)
    v = verdict(rs)
    with open(a.out, "w") as f:
        f.write(md(rs, v))
    if a.json:
        with open(a.json, "w") as f:
            json.dump({"rows": rs, "verdict": v}, f, indent=1)
    print(json.dumps({"arms": [r["arm"] for r in rs], "verdict": v, "out": a.out}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
