"""Publish a shard to a PRIVATE HF dataset repo, with a card a consumer can act on.

One repo per shard, contents of ds/ at the repo root, so a trainer can do
LeRobotDataset("cagataydev/strands-vla-rlenv-<shard>") with no extra arguments -- the lerobot convention.

The card is GENERATED from this lane's measurement JSONs, and it leads with what the shard can and cannot
support rather than with its size, because the size is the least informative thing about it:
  - goal necessity: how much of the score is earnable ONLY by reading the goal, per band
  - the success label: dwell, so a reader knows a "touch" is not a graze
  - the horizon, and whether the task is complete before it ends
  - the limits, including that these are scripted-expert rollouts in MuJoCo

Usage: python examples/rlenv/publish.py --shard so101-touch [--private] [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import os

DATA = os.path.expanduser("~/svla-rlenv-data")
RUNS = os.path.expanduser("~/.tiny/strands-vla-20261009/lanes/RLENV/runs")
PREFIX = "cagataydev/strands-vla-rlenv-"


def load(p):
    try:
        return json.load(open(p))
    except Exception:
        return None


def card(shard: str, rep: dict, nec: dict | None, dwl: dict | None, lb: dict | None,
         hor: dict | None, repo: str, cr: dict | None = None) -> str:
    b = rep.get("passB") or {}
    ts = rep.get("written_task_strings") or {}
    arm = rep.get("arm")
    L = [
        "---", "license: apache-2.0", "task_categories:", "- robotics",
        "tags:", "- lerobot", "- strands-vla", "- rlenv", f"- {arm}", "---", "",
        f"# {shard}", "",
        f"{b.get('parquet_episode_count')} episodes / {b.get('frames')} frames of "
        f"`{arm}` `{rep.get('task')}` in MuJoCo, generated by a scripted expert and kept only on success.",
        "", "```python", "from lerobot.datasets.lerobot_dataset import LeRobotDataset",
        f'ds = LeRobotDataset("{repo}")', "```", "",
        "## What this shard can and cannot support", "",
        "Read this before measuring a goal ablation on it. A shard with little goal headroom is not broken,",
        "but an ablation measured on it cannot distinguish a head that reads the goal from one that does not.",
        "",
    ]
    void = bool(cr and rep.get("task") == "touch"
                and "EXCEEDS" in str(cr.get("verdict", "")))
    if rep.get("task") == "touch" and cr:
        r = cr["radius_ee_to_centre_m"]
        L += ["### Embodied bound on the success criterion (decides whether a rate may be quoted)", "",
              "The criterion is a SURFACE gap: `mj_geomDistance` between any arm geom and the cube "
              f"<= {rep.get('touch_gap_m', 0.01)} m, where 0 is contact. That is not a radius around the "
              "cube centre, so it has to be converted before it can be compared to the project's "
              "embodied bound of 0.040 m. Measured at the instant the criterion fires, over "
              f"{cr['fired']} successes: the controlled point (the arm's IK reference site) sits "
              f"**{r['median']} m** from the cube centre (p95 {r['p95']}, max {r['max']}).", ""]
        if void:
            L += ["> **THESE SUCCESS RATES ARE VOID AND MUST NOT BE QUOTED.** The implied capture radius "
                  f"({r['p95']} m at p95) EXCEEDS the 0.040 m bound, so a success here can be declared "
                  "where no embodied contact occurred. A void cell is not a small result, it is no "
                  "result. The TRAJECTORIES remain usable as demonstrations; the success LABEL does not "
                  "support a claim. Cause: this arm's IK site sits far from its contacting geometry, so "
                  "the same surface-gap criterion implies a larger radius here than on so101 (0.027).", ""]
        elif r["max"] > 0.040:
            L += ["> **MARGINAL.** p95 clears the 0.040 m bound but the worst episode "
                  f"({r['max']} m) does not. Treat this cell as sitting ON the bound rather than "
                  "cleared, and do not build a headline on it.", ""]
    if nec:
        L += ["### Goal necessity (n=40/cell, 1 seed stream, EXPLORATORY — computed after the data "
              "were seen; simulation only, no real-robot evaluation)", "",
              "`goal-aware` is the expert planning to the true cube. `goal-blind` is the SAME code path",
              "planning to the CENTRE of the sampling band, cube left where it is. `headroom` is the part of",
              "the score only a goal-reader can earn.", "",
              "| band scale | goal-aware | goal-blind | headroom |", "|---|---|---|---|"]
        for r in nec["rows"]:
            L.append("| %s%s | %s | %s | **%s** |" % (
                r["band_scale"], " (this shard)" if abs(r["band_scale"] - float(
                    rep.get("band_scale", 1.0))) < 1e-9 else "",
                r["goal_aware"]["rate"], r["goal_blind"]["rate"], r["headroom"]))
        L.append("")
    if dwl:
        c = (dwl.get("cells") or {}).get("goal_aware")
        if c:
            L += ["### The success label is a dwell, not a graze", "",
                  f"The criterion is min-over-episode, so a one-tick graze would qualify. Measured on "
                  f"{dwl['episodes']} episodes of this arm: {c['labelled_success']} labelled successes, "
                  f"median dwell **{c['median_dwell_steps']} consecutive steps** within the touch gap, "
                  f"{c['terminal_within_gap']} still in contact at the final step, "
                  f"**{c['graze_only_dwell_1']} grazes**.", ""]
    if hor:
        rows = hor.get("rows") or []
        if len(rows) > 1:
            a0, a1 = rows[0], rows[-1]
            L += ["### Horizon", "",
                  f"Episodes are {rep.get('duration_s')} s at {rep.get('control_hz', 10)} Hz. The expert's "
                  f"own plan is {hor.get('shard_episode_s')} s, and the task is COMPLETE when it ends: at "
                  f"{a0['horizon_s']} s vs {a1['horizon_s']} s (step counts measured, not requested) the "
                  f"success rate is {a0['rate']} vs {a1['rate']} and the median displacement "
                  f"{a0['disp_end_median_mm']} mm vs {a1['disp_end_median_mm']} mm, with "
                  f"{a1['episodes_regressed_after_6s']}/{hor['episodes']} episodes disturbed afterwards. "
                  f"Frames past completion are the arm HOLDING its final pose.", ""]
    L += ["## Provenance and integrity", "",
          "| | |", "|---|---|",
          f"| expert success rate = the CEILING for this cell (cost of an episode) | "
          f"{'VOID (see bound above)' if void else rep['passA']['keep_rate']} |",
          f"| distinct goal-naming instructions | {ts.get('n')} |",
          f"| replay nondeterminism (re-replayed, actions not bit-exact) | "
          f"{len(b.get('replay_nondeterminism') or [])} |",
          f"| goal-sampling band scale | {rep.get('band_scale')} |",
          f"| scene code (strands-vla) | `{rep.get('svla_sha', 'see GEN-REPORT.json')}` |",
          ]
    if lb:
        L.append(f"| load-back through `LeRobotDataset` | {lb.get('verdict')} "
                 f"({lb.get('num_episodes')} eps, {lb.get('num_frames')} frames, "
                 f"keys {', '.join(lb.get('image_keys', []))}) |")
    L += ["", "`GEN-REPORT.json` in this repo carries every number above plus the per-episode seeds.", "",
          "## Limits", "",
          "- Simulation only; no real-robot evaluation.",
          "- MuJoCo, not a real arm. A scripted expert, not a learned policy: these bound what a head",
          "  trained here could demonstrate; they do not predict what one will.",
          "- Successes only, so the distribution contains no failures to learn from.",
          "- Necessity and dwell are n=40 per cell, on this arm and task only. Bands do NOT transfer",
          "  between arms: widening is free on so101/so100 and costs expert success on koch.",
          "- The goal controls a small fraction of the scene image (~0.1% mean absolute difference at",
          "  128px with a 2 cm cube), and the wrist view is goal-free at the reset pose.", ""]
    return "\n".join(L)


def main(argv=None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--shard", required=True)
    p.add_argument("--private", action="store_true", default=True)
    p.add_argument("--dry-run", action="store_true")
    a = p.parse_args(argv)

    d = os.path.join(DATA, a.shard)
    rep = load(os.path.join(d, "GEN-REPORT.json"))
    if not rep or rep.get("verdict") != "OK":
        print(json.dumps({"shard": a.shard, "refused": "no GEN-REPORT with verdict OK"}))
        return 1
    arm, task = rep.get("arm"), rep.get("task")
    nec = load(os.path.join(RUNS, f"necessity-{arm}-{task}.json"))
    dwl = load(os.path.join(RUNS, f"dwell-{arm}-touch.json"))
    lb = load(os.path.join(RUNS, f"loadback-{a.shard}.json"))
    cr = ((load(os.path.join(RUNS, "capture-radius.json")) or {}).get("arms") or {}).get(arm)
    hor = load(os.path.join(RUNS, f"horizon-{arm}-{task}.json"))
    repo = PREFIX + a.shard
    text = card(a.shard, rep, nec, dwl, lb, hor, repo, cr)
    open(os.path.join(d, "README.md"), "w").write(text)
    out = {"shard": a.shard, "repo": repo, "card_lines": len(text.splitlines()),
           "has_necessity": bool(nec), "has_dwell": bool(dwl), "has_loadback": bool(lb),
           "has_horizon": bool(hor), "private": bool(a.private)}
    if a.dry_run:
        print(json.dumps(out | {"dry_run": True}))
        return 0

    from huggingface_hub import HfApi
    api = HfApi()
    api.create_repo(repo, repo_type="dataset", private=a.private, exist_ok=True)
    api.upload_folder(repo_id=repo, repo_type="dataset", folder_path=os.path.join(d, "ds"),
                      commit_message=f"{a.shard}: lerobot shard")
    for f in ("GEN-REPORT.json", "README.md"):
        api.upload_file(path_or_fileobj=os.path.join(d, f), path_in_repo=f, repo_id=repo,
                        repo_type="dataset", commit_message=f"{a.shard}: {f}")
    # A dataset is not published until the CODEBASE_VERSION TAG exists. LeRobotDataset resolves a repo at
    # revision=CODEBASE_VERSION, not at main, so a repo with every file in place still fails to load with
    # RevisionNotFoundError. My LOCAL load-back passed and the HUB load-back did not, which is the whole
    # reason to test the consumer's actual route rather than the one I control.
    from lerobot.datasets.lerobot_dataset import CODEBASE_VERSION
    try:
        api.create_tag(repo, tag=CODEBASE_VERSION, repo_type="dataset", exist_ok=True)
        out["tag"] = CODEBASE_VERSION
    except Exception as exc:  # recorded, never swallowed: without the tag the repo is unusable
        out["tag_error"] = f"{type(exc).__name__}: {exc}"

    info = api.dataset_info(repo)
    out["sha"] = info.sha
    out["files"] = len(info.siblings or [])
    out["is_private"] = info.private
    print(json.dumps(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
