"""Publish a shard to a PRIVATE HF dataset repo, with a card a consumer can act on.

One repo per shard, contents of ds/ at the repo root, so a trainer can do
LeRobotDataset("cagataydev/strands-vla-rlenv-<shard>") with no extra arguments -- the lerobot convention.

The card is GENERATED from this lane's measurement JSONs, and it leads with what the shard can and cannot
support rather than with its size, because the size is the least informative thing about it:
  - goal necessity: how much of the score is earnable ONLY by reading the goal, per band
  - the success label: dwell, so a reader knows a "touch" is not a graze
  - the horizon, and whether the task is complete before it ends
  - the limits, including that these are scripted-expert rollouts in MuJoCo

Usage: python examples/rlenv/publish.py --shard so101-touch [--private] [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import os

DATA = os.path.expanduser("~/svla-rlenv-data")
RUNS = os.path.expanduser("~/.tiny/strands-vla-20261009/lanes/RLENV/runs")
PREFIX = "cagataydev/strands-vla-rlenv-"


def load(p):
    try:
        return json.load(open(p))
    except Exception:
        return None


def card(shard: str, rep: dict, nec: dict | None, dwl: dict | None, lb: dict | None,
         hor: dict | None, repo: str, cr: dict | None = None, pp: dict | None = None,
         sh: dict | None = None) -> str:
    b = rep.get("passB") or {}
    ts = rep.get("written_task_strings") or {}
    arm = rep.get("arm")
    L = [
        "---", "license: apache-2.0", "task_categories:", "- robotics",
        "tags:", "- lerobot", "- strands-vla", "- rlenv", f"- {arm}", "---", "",
        f"# {shard}", "",
        f"{b.get('parquet_episode_count')} episodes / {b.get('frames')} frames of ",
        (f"`{arm}` `{rep.get('task')}` in MuJoCo, generated by a scripted expert and kept only on success."
         if _cls(rep) == "successes" else
         f"**NEGATIVE SPLIT.** `{arm}` `{rep.get('task')}` in MuJoCo, same scripted expert and same bands as "
         f"the success shard, kept only when the success test FAILED. Every episode here is a FAILURE; the "
         f"pass-B gate refuses to publish if any replayed seed succeeds, so the class is single."),
        "", "```python", "from lerobot.datasets.lerobot_dataset import LeRobotDataset",
        f'ds = LeRobotDataset("{repo}")', "```", "",
        "## What this shard can and cannot support", "",
        *(["> **Inherited measurements.** This is a VARIANT shard "
           f"({', '.join([x for x in ((f'band_scale {rep.get(chr(98)+chr(97)+chr(110)+chr(100)+chr(95)+chr(115)+chr(99)+chr(97)+chr(108)+chr(101))}' if rep.get('band_scale') not in (None, 1.0) else ''), (f'episode {rep.get(chr(100)+chr(117)+chr(114)+chr(97)+chr(116)+chr(105)+chr(111)+chr(110)+chr(95)+chr(115))} s' if rep.get('duration_s') else '')) if x]) or 'non-default generation'}). "
           f"The criterion pricing, goal-necessity, dwell and capture-radius cells below were measured on the "
           f"canonical `{arm}-{rep.get('task')}` shard and are INHERITED here, not re-measured on this scene "
           "distribution: a wider band or a longer episode changes what an accidental success costs. The "
           "load-back, the per-episode goals and the keep rate below ARE this shard's own.", ""]
          if shard != f"{arm}-{rep.get('task')}" else []),
        "Read this before measuring a goal ablation on it. A shard with little goal headroom is not broken,",
        "but an ablation measured on it cannot distinguish a head that reads the goal from one that does not.",
        "",
    ]
    if rep.get("task") == "push" and pp:
        if _cls(rep) != "successes":
            L += _failure_modes(rep)
        L += ["### What the success criterion requires (priced against its own floors)", "",
              f"Success is cube displacement along the approach axis > **{pp.get('threshold_m', 0.04)} m**. A "
              "displacement threshold is worth nothing until the displacement a NON-pushing arm produces is "
              "measured, so it was priced with this harness's own negative controls on the same scenes, "
              f"seeds and episode length ({pp.get('episodes_per_cell')} episodes per cell):", "",
              "| arm policy | displacement along axis (median / max) | scored as success |",
              "|---|---|---|",
              f"| frozen arm (drift only) | {pp['hold']['along_m']['median']} / "
              f"{pp['hold']['along_m']['max']} m | {pp['hold']['would_be_scored_success']}/"
              f"{pp['hold']['n']} |",
              f"| random walk from rest | {pp['random']['along_m']['median']} / "
              f"{pp['random']['along_m']['max']} m | {pp['random']['would_be_scored_success']}/"
              f"{pp['random']['n']} |"]
        if sh and sh.get("along_m"):
            L += [f"| held at the CONTACT-ADJACENT pose, no stroke ({arm}) | {sh['along_m']['median']} / "
                  f"{sh['along_m']['max']} m | {sh['false_successes']}/{sh['n']} |"]
        L += [f"| scripted expert | {pp['expert']['along_m']['median']} / "
              f"{pp['expert']['along_m']['max']} m | {pp['expert']['would_be_scored_success']}/"
              f"{pp['expert']['n']} |", ""]
        L += ["The first two floors are **uninformative**: they produce exactly 0.000 m because an arm "
              "starting at rest never reaches the cube, so they show the cube does not DRIFT and say nothing "
              "about ACCIDENTAL pushes.", ""]
        if sh and sh.get("informative"):
            L += [f"The third row is the control that bites: the expert's own plan stopped BEFORE its stroke "
                  f"(so the gripper is adjacent to the cube and never sweeps) moved the cube at most "
                  f"{sh['along_m']['max']} m and scored {sh['false_successes']}/{sh['n']}. So the threshold is "
                  f"**{pp.get('margin_x')}x** the largest accidental push available from the best possible "
                  "starting pose: on this arm the criterion requires directed motion, not proximity.", "",
                  "This margin is PER ARM and newly measured. An earlier published margin (1.78x) was "
                  "withdrawn in it13: it came from one ad-hoc so101 cell that no committed script reproduces, "
                  "and it had been printed on all three arms' cards, including this one.", ""]
        elif sh:
            L += [f"The third row is the control that WOULD bite, and on this arm it does not: the pre-stroke "
                  f"pose moves the cube at most {sh['along_m']['max']} m, which is solver noise rather than "
                  "contact, so it bounds nothing. **No floor available on this arm bounds a false success, so "
                  "the soundness of this criterion here is UNDETERMINED.** A previously published margin "
                  "(1.78x) was withdrawn in it13: it came from an ad-hoc so101 cell that no committed script "
                  "reproduces, and it was printed on all three arms' cards.", ""]
        if pp.get("expert_median_along_m") is not None:
            L += ["### Validated ceiling (what the best available policy scores under this criterion)", "",
                  f"The scripted expert -- which has the cube pose and plans directly to it -- is scored by "
                  f"this same criterion at **{pp.get('expert_would_be_scored_success')}** episodes, with a "
                  f"median displacement of {pp['expert_median_along_m']} m."]
            if pp.get("push_min_exceeds_expert_median"):
                L += ["", f"**The threshold exceeds the expert's own median on this arm** "
                      f"({pp.get('threshold_m', 0.04)} m > {pp['expert_median_along_m']} m), so any push "
                      f"success rate measured here is bounded by that ceiling "
                      f"({pp.get('expert_would_be_scored_success')}), NOT by the policy under test. Compare a "
                      "policy against the ceiling, never against 100%.", ""]
            else:
                L += ["", "The expert's median clears the threshold on this arm, so the ceiling is a policy "
                      "bound rather than a criterion artefact.", ""]
    import glob as _g
    _ej = _g.glob(os.path.join(os.path.dirname(os.path.join(DATA, shard, "ds")), "ds", "EPISODES.jsonl"))
    if _ej:
        _n = sum(1 for _ in open(_ej[0]))
        L += ["### Per-episode goals (EPISODES.jsonl)", "",
              f"`EPISODES.jsonl` carries one row per episode -- `episode_index`, `seed`, `cube_x`, `cube_y`, "
              f"`arm`, `task` ({_n} rows) -- because the parquet does NOT: it has `action`, "
              "`observation.state`, the indices and timestamps, and no cube pose and no success flag. "
              "Without this file nothing on this card could be recomputed from the shard itself, and a "
              "sibling run has already lost its generation report and with it 200 goals. The rows were "
              "rebuilt from the generator's `kept_seeds` (the cube sampler is a pure function of arm, task "
              "and seed) and VERIFIED against the recorded actions: 6 of 9 expert keyframes per episode "
              "match the recorded action rows BIT-EXACTLY, while the same test run with the wrong random "
              "construction matches 0 of 9 and misses the cube-dependent poses by 0.39-0.65 rad. The one "
              "non-exact keyframe is the cube-INDEPENDENT rest pose, off by the identical 0.0145 rad under "
              "both constructions (start-pose jitter, not evidence either way).", ""]
    void = bool(cr and rep.get("task") == "touch"
                and "EXCEEDS" in str(cr.get("verdict", "")))
    if rep.get("task") == "touch" and cr:
        r = cr["radius_ee_to_centre_m"]
        L += ["### Embodied bound on the success criterion (decides whether a rate may be quoted)", "",
              "The criterion is a SURFACE gap: `mj_geomDistance` between any arm geom and the cube "
              f"<= {rep.get('touch_gap_m', 0.01)} m, where 0 is contact. That is not a radius around the "
              "cube centre, so it has to be converted before it can be compared to the project's "
              "embodied bound of 0.040 m. Measured at the instant the criterion fires, over "
              f"{cr['fired']} successes: the controlled point (the arm's IK reference site) sits "
              f"**{r['median']} m** from the cube centre (p95 {r['p95']}, max {r['max']}).", ""]
        if void:
            L += ["> **THESE SUCCESS RATES ARE VOID AND MUST NOT BE QUOTED.** The implied capture radius "
                  f"({r['p95']} m at p95) EXCEEDS the 0.040 m bound, so a success here can be declared "
                  "where no embodied contact occurred. A void cell is not a small result, it is no "
                  "result. The TRAJECTORIES remain usable as demonstrations; the success LABEL does not "
                  "support a claim. Cause: this arm's IK site sits far from its contacting geometry, so "
                  "the same surface-gap criterion implies a larger radius here than on so101 (0.027).", ""]
        elif r["max"] > 0.040:
            L += ["> **MARGINAL.** p95 clears the 0.040 m bound but the worst episode "
                  f"({r['max']} m) does not. Treat this cell as sitting ON the bound rather than "
                  "cleared, and do not build a headline on it.", ""]
    if nec:
        L += ["### Goal necessity (n=40/cell, 1 seed stream, EXPLORATORY — computed after the data "
              "were seen; simulation only, no real-robot evaluation)", "",
              "`goal-aware` is the expert planning to the true cube. `goal-blind` is the SAME code path",
              "planning to the CENTRE of the sampling band, cube left where it is. `headroom` is the part of",
              "the score only a goal-reader can earn.", "",
              "| band scale | goal-aware | goal-blind | headroom |", "|---|---|---|---|"]
        for r in nec["rows"]:
            L.append("| %s%s | %s | %s | **%s** |" % (
                r["band_scale"], " (this shard)" if abs(r["band_scale"] - float(
                    rep.get("band_scale", 1.0))) < 1e-9 else "",
                r["goal_aware"]["rate"], r["goal_blind"]["rate"], r["headroom"]))
        L.append("")
    if dwl:
        c = (dwl.get("cells") or {}).get("goal_aware")
        if c:
            L += ["### The success label is a dwell, not a graze", "",
                  f"The criterion is min-over-episode, so a one-tick graze would qualify. Measured on "
                  f"{dwl['episodes']} episodes of this arm: {c['labelled_success']} labelled successes, "
                  f"median dwell **{c['median_dwell_steps']} consecutive steps** within the touch gap, "
                  f"{c['terminal_within_gap']} still in contact at the final step, "
                  f"**{c['graze_only_dwell_1']} grazes**.", ""]
    if hor:
        rows = hor.get("rows") or []
        if len(rows) > 1:
            a0, a1 = rows[0], rows[-1]
            L += ["### Horizon", "",
                  f"Episodes are {rep.get('duration_s')} s at {rep.get('control_hz', 10)} Hz. The expert's "
                  f"own plan is {hor.get('shard_episode_s')} s, and the task is COMPLETE when it ends: at "
                  f"{a0['horizon_s']} s vs {a1['horizon_s']} s (step counts measured, not requested) the "
                  f"success rate is {a0['rate']} vs {a1['rate']} and the median displacement "
                  f"{a0['disp_end_median_mm']} mm vs {a1['disp_end_median_mm']} mm, with "
                  f"{a1['episodes_regressed_after_6s']}/{hor['episodes']} episodes disturbed afterwards. "
                  f"Frames past completion are the arm HOLDING its final pose.", ""]
    L += ["## Provenance and integrity", "",
          "| | |", "|---|---|",
          f"| expert success rate = the CEILING for this cell (cost of an episode) | "
          f"{'VOID (see bound above)' if void else rep['passA']['keep_rate']} |",
          f"| distinct goal-naming instructions | {ts.get('n')} |",
          f"| replay nondeterminism (re-replayed, actions not bit-exact) | "
          f"{len(b.get('replay_nondeterminism') or [])} |",
          f"| goal-sampling band scale | {rep.get('band_scale')} |",
          f"| scene code (strands-vla) | `{rep.get('svla_sha', 'see GEN-REPORT.json')}` |",
          ]
    if lb:
        L.append(f"| load-back through `LeRobotDataset` | {lb.get('verdict')} "
                 f"({lb.get('num_episodes')} eps, {lb.get('num_frames')} frames, "
                 f"keys {', '.join(lb.get('image_keys', []))}) |")
    L += ["", "`GEN-REPORT.json` in this repo carries every number above plus the per-episode seeds.", "",
          "## Limits", "",
          "- Simulation only; no real-robot evaluation.",
          "- MuJoCo, not a real arm. A scripted expert, not a learned policy: these bound what a head",
          "  trained here could demonstrate; they do not predict what one will.",
          "- Successes only, so the distribution contains no failures to learn from.",
          "- Necessity and dwell are n=40 per cell, on this arm and task only. Bands do NOT transfer",
          "  between arms: widening is free on so101/so100 and costs expert success on koch.",
          "- The goal controls a small fraction of the scene image (~0.1% mean absolute difference at",
          "  128px with a 2 cm cube), and the wrist view is goal-free at the reset pose.", ""]
    return "\n".join(L)


def _cls(rep) -> str:
    return ((rep.get("passB") or {}).get("outcome_class")) or "successes"


def _failure_modes(rep) -> list:
    """What a consumer of a NEGATIVE split has to know: failures are not interchangeable.

    Measured from the report's own per-episode gaps, because "it failed" is not a usable label -- a touch
    that misses by 0.4 mm and a push that never contacts the cube are different training signals.
    """
    eps = rep.get("kept_episodes") or []
    g = sorted(float(e["gap"]) for e in eps if e.get("gap") is not None)
    if not g:
        return []
    TOL = 0.01
    reached = sum(1 for x in g if x <= TOL)
    L = ["### Why these episodes failed (measured, not assumed)", "",
         f"Arm-to-cube gap over the {len(g)} failures: min {g[0] * 1000:.2f} mm, median "
         f"{g[len(g) // 2] * 1000:.2f} mm, max {g[-1] * 1000:.2f} mm, against a {TOL * 1000:.0f} mm touch "
         f"tolerance. **{reached} of {len(g)}** episodes did reach the cube; **{len(g) - reached}** never did.", ""]
    if rep.get("task") == "touch" and g[-1] <= 2 * TOL:
        L += [f"**Read this before training on it.** Every failure here is a NEAR MISS: the worst one is "
              f"{g[-1] * 1000:.2f} mm from a {TOL * 1000:.0f} mm tolerance, i.e. all of them fail by at most "
              f"{(g[-1] - TOL) * 1000:.2f} mm. This split therefore teaches a millimetre-scale boundary, not "
              f"a behavioural difference, and a failure-aware objective trained on it is learning the "
              f"tolerance rather than the task. Prefer the push negative split for that purpose.", ""]
    elif reached > 0.9 * len(g):
        L += [f"**These are behavioural failures.** {reached} of {len(g)} episodes made contact and still "
              f"failed the displacement threshold, so the policy's error is in the push, not in reaching. "
              f"This is the split to use for a failure-aware objective.", ""]
    return L


def main(argv=None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--shard", required=True)
    p.add_argument("--private", action="store_true", default=True)
    p.add_argument("--dry-run", action="store_true")
    a = p.parse_args(argv)

    d = os.path.join(DATA, a.shard)
    rep = load(os.path.join(d, "GEN-REPORT.json"))
    if not rep or rep.get("verdict") != "OK":
        print(json.dumps({"shard": a.shard, "refused": "no GEN-REPORT with verdict OK"}))
        return 1
    arm, task = rep.get("arm"), rep.get("task")
    # it20 debt, paid: these were keyed on arm+task only, so a NEGATIVE split or a band variant printed the
    # POSITIVE shard's necessity and dwell numbers as its own. Shard-keyed first; an inherited cell is still
    # allowed (it is an arm property, not a shard property) but it must be LABELLED, never silent.
    nec = load(os.path.join(RUNS, f"necessity-{a.shard}.json"))
    dwl = load(os.path.join(RUNS, f"dwell-{a.shard}.json"))
    inherited = []
    if nec is None:
        nec = load(os.path.join(RUNS, f"necessity-{arm}-{task}.json"))
        if nec is not None and a.shard != f"{arm}-{task}":
            nec = dict(nec, inherited_from=f"{arm}-{task}")
            inherited.append("necessity")
    if dwl is None:
        dwl = load(os.path.join(RUNS, f"dwell-{arm}-touch.json"))
        if dwl is not None and a.shard != f"{arm}-{task}":
            dwl = dict(dwl, inherited_from=f"{arm}-touch")
            inherited.append("dwell")
    lb = load(os.path.join(RUNS, f"loadback-{a.shard}.json"))
    cr = ((load(os.path.join(RUNS, "capture-radius.json")) or {}).get("arms") or {}).get(arm)
    pp = ((load(os.path.join(RUNS, "price-push.json")) or {}).get("arms") or {}).get(arm)
    # it13/D212: the control is now per-arm and lives inside price-push.json. The old line loaded
    # push-sharp-so101.json -- an ad-hoc, unreproducible so101 cell -- and printed it on EVERY arm's card.
    sh = (pp or {}).get("behind")
    # Per-shard artefacts must be looked up BY SHARD first. Keyed only on arm+task, a negative split or a
    # band variant silently inherits the POSITIVE shard's load-back and horizon verdicts and prints them as
    # its own -- the inheritance trap it17 fixed for the criterion cells, in a second place.
    hor = (load(os.path.join(RUNS, f"horizon-{a.shard}.json"))
           or load(os.path.join(RUNS, f"horizon-{arm}-{task}.json")))
    for _p in (f"load-back-{a.shard}.json", f"loadback-{a.shard}.json"):
        _own = load(os.path.join(RUNS, _p))
        if _own:
            lb = _own
            break
    else:
        if a.shard not in (f"{arm}-{task}",):
            lb = None  # refuse to print another shard's load-back as this one's
    repo = PREFIX + a.shard
    text = card(a.shard, rep, nec, dwl, lb, hor, repo, cr, pp, sh)
    open(os.path.join(d, "README.md"), "w").write(text)
    out = {"shard": a.shard, "repo": repo, "card_lines": len(text.splitlines()),
           "has_necessity": bool(nec), "has_dwell": bool(dwl), "has_loadback": bool(lb),
           "has_horizon": bool(hor), "private": bool(a.private)}
    if a.dry_run:
        print(json.dumps(out | {"dry_run": True}))
        return 0

    from huggingface_hub import HfApi
    api = HfApi()
    api.create_repo(repo, repo_type="dataset", private=a.private, exist_ok=True)
    api.upload_folder(repo_id=repo, repo_type="dataset", folder_path=os.path.join(d, "ds"),
                      commit_message=f"{a.shard}: lerobot shard")
    for f in ("GEN-REPORT.json", "README.md"):
        api.upload_file(path_or_fileobj=os.path.join(d, f), path_in_repo=f, repo_id=repo,
                        repo_type="dataset", commit_message=f"{a.shard}: {f}")
    # A dataset is not published until the CODEBASE_VERSION TAG exists. LeRobotDataset resolves a repo at
    # revision=CODEBASE_VERSION, not at main, so a repo with every file in place still fails to load with
    # RevisionNotFoundError. My LOCAL load-back passed and the HUB load-back did not, which is the whole
    # reason to test the consumer's actual route rather than the one I control.
    from lerobot.datasets.lerobot_dataset import CODEBASE_VERSION
    try:
        api.create_tag(repo, tag=CODEBASE_VERSION, repo_type="dataset", exist_ok=True)
        out["tag"] = CODEBASE_VERSION
    except Exception as exc:  # recorded, never swallowed: without the tag the repo is unusable
        out["tag_error"] = f"{type(exc).__name__}: {exc}"

    info = api.dataset_info(repo)
    out["sha"] = info.sha
    out["files"] = len(info.siblings or [])
    out["is_private"] = info.private
    print(json.dumps(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
