#!/usr/bin/env python
"""Regenerate ``strands_robots/registry/urdf_robots.json`` from built URDF assets.

The file lists every ``robot_descriptions`` URDF-only robot the MuJoCo backend
serves (``list_urdf_only()``: a URDF description, no MJCF sibling, not curated)
with the facts the registry and the docs report without importing anything:
category, actuated joint count, floating base, upstream pin, mesh formats,
whether the meshes stream unchanged. Every number comes from an asset the
loader actually built (``urdf_asset.json`` next to ``robot.xml``), so the
``joints`` a page prints is the compiled model's ``nu`` and cannot drift from
it. A robot that did not build is listed with ``has_sim: false`` and the
loader's refusal sentence.

Usage (builds what is missing, then writes the file)::

    python scripts/build_urdf_registry.py            # every URDF-only robot
    python scripts/build_urdf_registry.py ur10 pr2   # a subset, others kept

Building imports the description modules, which clones the upstream
repositories on first use (about 5 GB for the whole set).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from strands_robots.assets.urdf import (  # noqa: E402
    UrdfBuildError,
    build_urdf_asset,
    category_for_tags,
    is_floating,
    read_asset_info,
)
from strands_robots.registry.discovery import list_urdf_only, urdf_descriptions_module  # noqa: E402
from strands_robots.utils import get_assets_dir  # noqa: E402

OUT = REPO / "strands_robots" / "registry" / "urdf_robots.json"

COMMENT = (
    "Generated by scripts/build_urdf_registry.py from assets strands_robots.assets.urdf built; do not hand-edit. "
    "robot_descriptions URDF-only robots the MuJoCo backend compiles on first use. "
    "joints is the compiled model's actuator count; has_sim false carries the loader's refusal."
)


def _tags(module: str) -> list[str]:
    from robot_descriptions._descriptions import DESCRIPTIONS  # type: ignore[import-not-found]

    return sorted(getattr(DESCRIPTIONS.get(module), "tags", ()) or ())


def _version() -> str:
    try:
        from importlib.metadata import version

        return version("robot_descriptions")
    except Exception:  # pragma: no cover - metadata absent in odd installs
        return "unknown"


def entry_for(name: str, *, build: bool) -> dict[str, object]:
    module = urdf_descriptions_module(name)
    assert module is not None, name
    tags = _tags(module)
    asset_dir = get_assets_dir() / module
    info = read_asset_info(asset_dir)
    refusal: str | None = None
    if info is None and build:
        try:
            build_urdf_asset(name, module, get_assets_dir())
            info = read_asset_info(asset_dir)
        except UrdfBuildError as exc:
            refusal = str(exc)
        except Exception as exc:  # a crash is a refusal with the exception as its sentence
            refusal = f"{type(exc).__name__}: {str(exc).splitlines()[0][:160]}"
    if info is None:
        return {
            "module": module,
            "tags": tags,
            "category": category_for_tags(tags),
            "floating": is_floating(tags),
            "has_sim": False,
            "refusal": refusal or "not built",
        }
    return {
        "module": module,
        "tags": tags,
        "category": str(info["category"]),
        "joints": int(info["nu"]),
        "nq": int(info["nq"]),
        "floating": bool(info["floating"]),
        "repository": info.get("repository"),
        "commit": info.get("commit"),
        "mesh_formats": sorted({str(m["ext"]) for m in info.get("meshes", [])}),
        "streamable": bool(info.get("streamable")),
        "has_sim": True,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("names", nargs="*", help="robots to (re)build; default: every URDF-only robot")
    parser.add_argument("--no-build", action="store_true", help="only read assets already on disk")
    args = parser.parse_args(argv)

    existing: dict[str, dict[str, object]] = {}
    if OUT.exists():
        existing = json.loads(OUT.read_text(encoding="utf-8")).get("robots", {})
    names = args.names or list_urdf_only()
    robots = dict(existing)
    for name in names:
        robots[name] = entry_for(name, build=not args.no_build)
        print(f"{name:22s} {'sim' if robots[name]['has_sim'] else 'refused: ' + str(robots[name].get('refusal'))}")
    # A name that left the URDF-only set (a new MJCF sibling, a curated entry) leaves the file.
    keep = set(list_urdf_only())
    robots = {n: robots[n] for n in sorted(robots) if n in keep}
    doc = {"_comment": COMMENT, "robot_descriptions_version": _version(), "robots": robots}
    OUT.write_text(json.dumps(doc, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    built = sum(1 for r in robots.values() if r["has_sim"])
    print(f"wrote {OUT.relative_to(REPO)}: {len(robots)} robots, {built} with sim")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
